const ActionTypes = {
    SET_USER: "SET_USER",
    SET_TOKENS: "SET_TOKENS",
    LOGOUT: "LOGOUT",
    UPDATE_BUSINESS_FORM:"UPDATE_BUSINESS_FORM",
    SET_BUSINESS:"SET_BUSINESS",
    SET_LOCATION:"SET_LOCATION",
    SET_MERCHANT:"SET_MERCHANT",
    SET_USER_PROFILE:"SET_USER_PROFILE",
    SET_USER_COLLECTION:"SET_USER_COLLECTION",
    SET_GALLERY_IMAGE:"SET_GALLERY_IMAGE",
    SET_TALKS:"SET_TALKS",
    SET_BUSINESS_GALLERY:"SET_BUSINESS_GALLERY",
    SET_BUSINESS_MENU:"SET_BUSINESS_MENU",
    SET_COUNTRIES:"SET_COUNTRIES",
    SET_EVENTS:"SET_EVENTS",
    SET_APPLE_USER:"SET_APPLE_USER",
    SET_HOME:"SET_HOME",
}

export default ActionTypes